const vinylRecords = [
  {
    title: "21",
    artist: "Adele",
    genre: "Pop",
    releaseYear: 2011,
    price: 25.99,
    imageUrl:
      "https://cdn.webshopapp.com/shops/13847/files/411011941/650x650x2/adele-21-vinyl-lp.jpg",
    altText: "",
  },
  {
    title: "To Pimp a Butterfly",
    artist: "Kendrick Lamar",
    genre: "Hip Hop",
    releaseYear: 2015,
    price: 29.99,
    imageUrl:
      "https://thesoundofvinyl.com.au/cdn/shop/products/kendrick-lamar-to-pimp-a-butterfly-2lp.jpg?v=1607471363",
    altText: "",
  },
  {
    title: "AM",
    artist: "Arctic Monkeys",
    genre: "Rock",
    releaseYear: 2013,
    price: 24.99,
    imageUrl: "https://www.dominomusic.com/res/8yX5/2018am.jpg",
    altText: "",
  },
  {
    title: "Random Access Memories",
    artist: "Daft Punk",
    genre: "Electronic",
    releaseYear: 2013,
    price: 29.99,
    imageUrl:
      "https://uturnaudio.com/cdn/shop/products/daft_punk_album_950x.jpg?v=1632321483",
    altText: "",
  },
  {
    title: "Future Nostalgia",
    artist: "Dua Lipa",
    genre: "Pop",
    releaseYear: 2020,
    price: 27.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "Born to Die",
    artist: "Lana Del Rey",
    genre: "Pop",
    releaseYear: 2012,
    price: 26.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "In the Aeroplane Over the Sea",
    artist: "Neutral Milk Hotel",
    genre: "Indie Rock",
    releaseYear: 1998,
    price: 23.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "The Black Parade",
    artist: "My Chemical Romance",
    genre: "Rock",
    releaseYear: 2006,
    price: 24.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "folklore",
    artist: "Taylor Swift",
    genre: "Indie Folk",
    releaseYear: 2020,
    price: 28.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "Channel Orange",
    artist: "Frank Ocean",
    genre: "R&B",
    releaseYear: 2012,
    price: 26.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "Lemonade",
    artist: "Beyoncé",
    genre: "R&B",
    releaseYear: 2016,
    price: 29.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "Demon Days",
    artist: "Gorillaz",
    genre: "Alternative",
    releaseYear: 2005,
    price: 24.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "The Life of Pablo",
    artist: "Kanye West",
    genre: "Hip Hop",
    releaseYear: 2016,
    price: 27.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "Back to Black",
    artist: "Amy Winehouse",
    genre: "Soul",
    releaseYear: 2006,
    price: 25.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "The Suburbs",
    artist: "Arcade Fire",
    genre: "Indie Rock",
    releaseYear: 2010,
    price: 24.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "Good Kid, M.A.A.D City",
    artist: "Kendrick Lamar",
    genre: "Hip Hop",
    releaseYear: 2012,
    price: 29.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "Electric Ladyland",
    artist: "The Jimi Hendrix Experience",
    genre: "Rock",
    releaseYear: 1968,
    price: 27.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "The 20/20 Experience",
    artist: "Justin Timberlake",
    genre: "Pop",
    releaseYear: 2013,
    price: 26.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "What a Time to Be Alive",
    artist: "Drake & Future",
    genre: "Hip Hop",
    releaseYear: 2015,
    price: 28.99,
    imageUrl: "",
    altText: "",
  },
  {
    title: "Hozier",
    artist: "Hozier",
    genre: "Indie Rock",
    releaseYear: 2014,
    price: 24.99,
    imageUrl: "",
    altText: "",
  },
];
export { vinylRecords };
